Output demo.gif
Set FontSize 18
Set Width 1920
Set Height 1080
Set Theme "GruvboxDark"
Set FontFamily "MesloLGS Nerd Font"
Set LineHeight 1.2

Set Shell zsh
Type@80ms "kplay local-proto"
Enter
Sleep 1500ms
Type "?"
Sleep 2000ms
Type "q"
Sleep 1s
Type "n"
Sleep 1s
Type "n"
Sleep 400ms
Type "j"
Sleep 1s
Type "n"
Sleep 400ms
Type "j"
Sleep 1s
Type "N"
Sleep 1000ms
Screenshot screenshots/one.png
Type@1000ms "jjjj"
Sleep 2s
