profiles:
  - name: json-encoded
    authentication: none
    encodingFormat: json
    brokers:
      - 127.0.0.1:9092
    topic: kplay-test-1

  - name: proto-encoded
    authentication: aws_msk_iam
    encodingFormat: protobuf
    protoConfig:
      descriptorSetFile: path/to/descriptor/set/file.pb
      descriptorName: sample.DescriptorName
    brokers:
      - 127.0.0.1:9092
    topic: kplay-test-2

  - name: raw
    authentication: none
    encodingFormat: raw
    brokers:
      - 127.0.0.1:9092
    topic: kplay-test-3

  - name: tls-enabled
    authentication: none
    encodingFormat: json
    tlsConfig:
      enabled: true
      insecureSkipVerify: false
    brokers:
      - kafka.example.com:9093
    topic: kplay-test-tls

  - name: tls-insecure
    authentication: none
    encodingFormat: json
    tlsConfig:
      enabled: true
      insecureSkipVerify: true
    brokers:
      - kafka-dev.example.com:9093
    topic: kplay-test-tls-insecure
