name: test

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".github/workflows/test.yml"

env:
  GO_VERSION: '1.24.2'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests
        env:
          INTEGRATION: "1"
        run: go test ./... -v
